# Generated by Django 2.0.1 on 2018-02-15 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macs', '0003_auto_20180201_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='member',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='memberpermission',
            name='deleted',
        ),
    ]
