# Generated by Django 2.0.1 on 2018-02-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macs', '0004_auto_20180215_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_rfid',
            field=models.TextField(default=''),
        ),
    ]
