# Generated by Django 2.0.1 on 2018-02-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macs', '0005_member_member_rfid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='machines',
        ),
        migrations.AddField(
            model_name='machine',
            name='members',
            field=models.ManyToManyField(through='macs.MemberPermission', to='macs.Member'),
        ),
    ]
