# Generated by Django 2.0.1 on 2018-02-27 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('macs', '0007_auto_20180227_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=False, to='macs.Machine')),
                ('member', models.ForeignKey(on_delete=False, to='macs.Member')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_macs.machineunlock_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
