# Generated by Django 2.0.1 on 2018-02-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('macs', '0009_machinelock'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=False, to='macs.Machine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_rfid',
        ),
        migrations.AddField(
            model_name='invalidrequest',
            name='member',
            field=models.ForeignKey(on_delete=False, to='macs.Member'),
        ),
        migrations.AddField(
            model_name='invalidrequest',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_macs.invalidrequest_set+', to='contenttypes.ContentType'),
        ),
    ]
